//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    这段代码是由 SntBackend.EntityGenerate 项目生成的，代码不需要任何修改就可以使用。
//    不要在生成文件中做任何修改，会被覆盖。
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using AutoMapper;
using SntBackend.DomainService.Share.Po;
using System;

namespace SntBackend.Application.Po.Dto
{
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// AccChargeCodeMapProfile
    /// </summary>
    public partial class AccChargeCodeMapProfile : Profile
    {
        public AccChargeCodeMapProfile()
        {
            CreateMap<AccChargeCodeCreateUpdateDtoInput, AccChargeCode>();
            CreateMap<AccChargeCode, AccChargeCodeDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// AccTransactionHeaderMapProfile
    /// </summary>
    public partial class AccTransactionHeaderMapProfile : Profile
    {
        public AccTransactionHeaderMapProfile()
        {
            CreateMap<AccTransactionHeaderCreateUpdateDtoInput, AccTransactionHeader>();
            CreateMap<AccTransactionHeader, AccTransactionHeaderDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// AccTransactionLinesMapProfile
    /// </summary>
    public partial class AccTransactionLinesMapProfile : Profile
    {
        public AccTransactionLinesMapProfile()
        {
            CreateMap<AccTransactionLinesCreateUpdateDtoInput, AccTransactionLines>();
            CreateMap<AccTransactionLines, AccTransactionLinesDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// AccTransactionMatchLinkMapProfile
    /// </summary>
    public partial class AccTransactionMatchLinkMapProfile : Profile
    {
        public AccTransactionMatchLinkMapProfile()
        {
            CreateMap<AccTransactionMatchLinkCreateUpdateDtoInput, AccTransactionMatchLink>();
            CreateMap<AccTransactionMatchLink, AccTransactionMatchLinkDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// GlbBranchMapProfile
    /// </summary>
    public partial class GlbBranchMapProfile : Profile
    {
        public GlbBranchMapProfile()
        {
            CreateMap<GlbBranchCreateUpdateDtoInput, GlbBranch>();
            CreateMap<GlbBranch, GlbBranchDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// GlbCompanyMapProfile
    /// </summary>
    public partial class GlbCompanyMapProfile : Profile
    {
        public GlbCompanyMapProfile()
        {
            CreateMap<GlbCompanyCreateUpdateDtoInput, GlbCompany>();
            CreateMap<GlbCompany, GlbCompanyDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// GlbStaffMapProfile
    /// </summary>
    public partial class GlbStaffMapProfile : Profile
    {
        public GlbStaffMapProfile()
        {
            CreateMap<GlbStaffCreateUpdateDtoInput, GlbStaff>();
            CreateMap<GlbStaff, GlbStaffDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// JobConShipLinkMapProfile
    /// </summary>
    public partial class JobConShipLinkMapProfile : Profile
    {
        public JobConShipLinkMapProfile()
        {
            CreateMap<JobConShipLinkCreateUpdateDtoInput, JobConShipLink>();
            CreateMap<JobConShipLink, JobConShipLinkDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// JobConsolMapProfile
    /// </summary>
    public partial class JobConsolMapProfile : Profile
    {
        public JobConsolMapProfile()
        {
            CreateMap<JobConsolCreateUpdateDtoInput, JobConsol>();
            CreateMap<JobConsol, JobConsolDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// JobHeaderMapProfile
    /// </summary>
    public partial class JobHeaderMapProfile : Profile
    {
        public JobHeaderMapProfile()
        {
            CreateMap<JobHeaderCreateUpdateDtoInput, JobHeader>();
            CreateMap<JobHeader, JobHeaderDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// JobShipmentMapProfile
    /// </summary>
    public partial class JobShipmentMapProfile : Profile
    {
        public JobShipmentMapProfile()
        {
            CreateMap<JobShipmentCreateUpdateDtoInput, JobShipment>();
            CreateMap<JobShipment, JobShipmentDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// OrgAddressMapProfile
    /// </summary>
    public partial class OrgAddressMapProfile : Profile
    {
        public OrgAddressMapProfile()
        {
            CreateMap<OrgAddressCreateUpdateDtoInput, OrgAddress>();
            CreateMap<OrgAddress, OrgAddressDtoOutput>();
        }
    }
    /// <summary>
    /// AutoMapper Profile 实体映射文件
    /// OrgHeaderMapProfile
    /// </summary>
    public partial class OrgHeaderMapProfile : Profile
    {
        public OrgHeaderMapProfile()
        {
            CreateMap<OrgHeaderCreateUpdateDtoInput, OrgHeader>();
            CreateMap<OrgHeader, OrgHeaderDtoOutput>();
        }
    }
}
