//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    这段代码是由 SntBackend.EntityGenerate 项目生成的，代码不需要任何修改就可以使用。
//    不要在生成文件中做任何修改，会被覆盖。
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using Abp.EntityFrameworkCore;
using SntBackend.DomainService.Share.Po;
using SntBackend.DomainService.Share.Repositories;

namespace SntBackend.SqlServer.EntityFrameworkCore.Repositories
{
    /// <summary>
    /// 
    /// AccChargeCodeRepository
    /// </summary>
    public partial class AccChargeCodeRepository : SqlServerEfCoreRepositoryBase<AccChargeCode, string>, IAccChargeCodeRepository
    {
        public AccChargeCodeRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// AccTransactionHeaderRepository
    /// </summary>
    public partial class AccTransactionHeaderRepository : SqlServerEfCoreRepositoryBase<AccTransactionHeader, string>, IAccTransactionHeaderRepository
    {
        public AccTransactionHeaderRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// AccTransactionLinesRepository
    /// </summary>
    public partial class AccTransactionLinesRepository : SqlServerEfCoreRepositoryBase<AccTransactionLines, string>, IAccTransactionLinesRepository
    {
        public AccTransactionLinesRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// AccTransactionMatchLinkRepository
    /// </summary>
    public partial class AccTransactionMatchLinkRepository : SqlServerEfCoreRepositoryBase<AccTransactionMatchLink, string>, IAccTransactionMatchLinkRepository
    {
        public AccTransactionMatchLinkRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// GlbBranchRepository
    /// </summary>
    public partial class GlbBranchRepository : SqlServerEfCoreRepositoryBase<GlbBranch, string>, IGlbBranchRepository
    {
        public GlbBranchRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// GlbCompanyRepository
    /// </summary>
    public partial class GlbCompanyRepository : SqlServerEfCoreRepositoryBase<GlbCompany, string>, IGlbCompanyRepository
    {
        public GlbCompanyRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// GlbStaffRepository
    /// </summary>
    public partial class GlbStaffRepository : SqlServerEfCoreRepositoryBase<GlbStaff, string>, IGlbStaffRepository
    {
        public GlbStaffRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// JobConShipLinkRepository
    /// </summary>
    public partial class JobConShipLinkRepository : SqlServerEfCoreRepositoryBase<JobConShipLink, string>, IJobConShipLinkRepository
    {
        public JobConShipLinkRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// JobConsolRepository
    /// </summary>
    public partial class JobConsolRepository : SqlServerEfCoreRepositoryBase<JobConsol, string>, IJobConsolRepository
    {
        public JobConsolRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// JobContainerRepository
    /// </summary>
    public partial class JobContainerRepository : SqlServerEfCoreRepositoryBase<JobContainer, string>, IJobContainerRepository
    {
        public JobContainerRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// JobDocAddressRepository
    /// </summary>
    public partial class JobDocAddressRepository : SqlServerEfCoreRepositoryBase<JobDocAddress, string>, IJobDocAddressRepository
    {
        public JobDocAddressRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// JobDocumentDataRepository
    /// </summary>
    public partial class JobDocumentDataRepository : SqlServerEfCoreRepositoryBase<JobDocumentData, string>, IJobDocumentDataRepository
    {
        public JobDocumentDataRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// JobHeaderRepository
    /// </summary>
    public partial class JobHeaderRepository : SqlServerEfCoreRepositoryBase<JobHeader, string>, IJobHeaderRepository
    {
        public JobHeaderRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// JobPackLinesRepository
    /// </summary>
    public partial class JobPackLinesRepository : SqlServerEfCoreRepositoryBase<JobPackLines, string>, IJobPackLinesRepository
    {
        public JobPackLinesRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// JobShipmentRepository
    /// </summary>
    public partial class JobShipmentRepository : SqlServerEfCoreRepositoryBase<JobShipment, string>, IJobShipmentRepository
    {
        public JobShipmentRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// OrgAddressRepository
    /// </summary>
    public partial class OrgAddressRepository : SqlServerEfCoreRepositoryBase<OrgAddress, string>, IOrgAddressRepository
    {
        public OrgAddressRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

    /// <summary>
    /// 
    /// OrgHeaderRepository
    /// </summary>
    public partial class OrgHeaderRepository : SqlServerEfCoreRepositoryBase<OrgHeader, string>, IOrgHeaderRepository
    {
        public OrgHeaderRepository(IDbContextProvider<SntBackendSqlServerDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }
    }

}
