//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    这段代码是由 SntBackend.EntityGenerate 项目生成的，代码不需要任何修改就可以使用。
//    不要在生成文件中做任何修改，会被覆盖。
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using SntBackend.DomainService.Share.Repositories;

namespace SntBackend.DomainService.Repositories
{
    /// <summary>
    /// 实体的仓储服务
    /// IRepositoryService
    /// </summary>
    public partial interface IRepositoryService
    {
        /// <summary>
        /// </summary>
        IAccChargeCodeRepository AccChargeCodeRepository { get; }
        /// <summary>
        /// </summary>
        IAccTransactionHeaderRepository AccTransactionHeaderRepository { get; }
        /// <summary>
        /// </summary>
        IAccTransactionLinesRepository AccTransactionLinesRepository { get; }
        /// <summary>
        /// </summary>
        IAccTransactionMatchLinkRepository AccTransactionMatchLinkRepository { get; }
        /// <summary>
        /// </summary>
        IGlbBranchRepository GlbBranchRepository { get; }
        /// <summary>
        /// </summary>
        IGlbCompanyRepository GlbCompanyRepository { get; }
        /// <summary>
        /// </summary>
        IGlbStaffRepository GlbStaffRepository { get; }
        /// <summary>
        /// </summary>
        IJobConShipLinkRepository JobConShipLinkRepository { get; }
        /// <summary>
        /// </summary>
        IJobConsolRepository JobConsolRepository { get; }
        /// <summary>
        /// </summary>
        IJobHeaderRepository JobHeaderRepository { get; }
        /// <summary>
        /// </summary>
        IJobShipmentRepository JobShipmentRepository { get; }
        /// <summary>
        /// </summary>
        IOrgAddressRepository OrgAddressRepository { get; }
        /// <summary>
        /// </summary>
        IOrgHeaderRepository OrgHeaderRepository { get; }
    }
}
