//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    这段代码是由 SntBackend.EntityGenerate 项目生成的，代码不需要任何修改就可以使用。
//    不要在生成文件中做任何修改，会被覆盖。
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using SntBackend.DomainService.Share.Repositories;
using Abp.Dependency;

namespace SntBackend.DomainService.Repositories
{
    /// <summary>
    /// 实体的仓储服务
    /// RepositoryService
    /// </summary>
    public partial class RepositoryService: IRepositoryService, ISingletonDependency
    {
        /// <summary>
        /// </summary>
        public IAccChargeCodeRepository AccChargeCodeRepository => IocManager.Instance.Resolve<IAccChargeCodeRepository>();
        /// <summary>
        /// </summary>
        public IAccTransactionHeaderRepository AccTransactionHeaderRepository => IocManager.Instance.Resolve<IAccTransactionHeaderRepository>();
        /// <summary>
        /// </summary>
        public IAccTransactionLinesRepository AccTransactionLinesRepository => IocManager.Instance.Resolve<IAccTransactionLinesRepository>();
        /// <summary>
        /// </summary>
        public IAccTransactionMatchLinkRepository AccTransactionMatchLinkRepository => IocManager.Instance.Resolve<IAccTransactionMatchLinkRepository>();
        /// <summary>
        /// </summary>
        public IGlbBranchRepository GlbBranchRepository => IocManager.Instance.Resolve<IGlbBranchRepository>();
        /// <summary>
        /// </summary>
        public IGlbCompanyRepository GlbCompanyRepository => IocManager.Instance.Resolve<IGlbCompanyRepository>();
        /// <summary>
        /// </summary>
        public IGlbStaffRepository GlbStaffRepository => IocManager.Instance.Resolve<IGlbStaffRepository>();
        /// <summary>
        /// </summary>
        public IJobConShipLinkRepository JobConShipLinkRepository => IocManager.Instance.Resolve<IJobConShipLinkRepository>();
        /// <summary>
        /// </summary>
        public IJobConsolRepository JobConsolRepository => IocManager.Instance.Resolve<IJobConsolRepository>();
        /// <summary>
        /// </summary>
        public IJobHeaderRepository JobHeaderRepository => IocManager.Instance.Resolve<IJobHeaderRepository>();
        /// <summary>
        /// </summary>
        public IJobShipmentRepository JobShipmentRepository => IocManager.Instance.Resolve<IJobShipmentRepository>();
        /// <summary>
        /// </summary>
        public IOrgAddressRepository OrgAddressRepository => IocManager.Instance.Resolve<IOrgAddressRepository>();
        /// <summary>
        /// </summary>
        public IOrgHeaderRepository OrgHeaderRepository => IocManager.Instance.Resolve<IOrgHeaderRepository>();
    }
}
