//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    这段代码是由 SntBackend.EntityGenerate 项目生成的，代码不需要任何修改就可以使用。
//    不要在生成文件中做任何修改，会被覆盖。
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using Abp.Domain.Repositories;
using SntBackend.DomainService.Share.Po;

namespace SntBackend.DomainService.Share.Repositories
{
    /// <summary>
    /// 
    /// IAccChargeCodeRepository
    /// </summary>
    public partial interface IAccChargeCodeRepository : IRepository<AccChargeCode, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IAccTransactionHeaderRepository
    /// </summary>
    public partial interface IAccTransactionHeaderRepository : IRepository<AccTransactionHeader, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IAccTransactionLinesRepository
    /// </summary>
    public partial interface IAccTransactionLinesRepository : IRepository<AccTransactionLines, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IAccTransactionMatchLinkRepository
    /// </summary>
    public partial interface IAccTransactionMatchLinkRepository : IRepository<AccTransactionMatchLink, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IGlbBranchRepository
    /// </summary>
    public partial interface IGlbBranchRepository : IRepository<GlbBranch, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IGlbCompanyRepository
    /// </summary>
    public partial interface IGlbCompanyRepository : IRepository<GlbCompany, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IGlbStaffRepository
    /// </summary>
    public partial interface IGlbStaffRepository : IRepository<GlbStaff, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IJobConShipLinkRepository
    /// </summary>
    public partial interface IJobConShipLinkRepository : IRepository<JobConShipLink, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IJobConsolRepository
    /// </summary>
    public partial interface IJobConsolRepository : IRepository<JobConsol, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IJobHeaderRepository
    /// </summary>
    public partial interface IJobHeaderRepository : IRepository<JobHeader, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IJobShipmentRepository
    /// </summary>
    public partial interface IJobShipmentRepository : IRepository<JobShipment, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IOrgAddressRepository
    /// </summary>
    public partial interface IOrgAddressRepository : IRepository<OrgAddress, string>, Abp.Dependency.ITransientDependency
    {
    }

    /// <summary>
    /// 
    /// IOrgHeaderRepository
    /// </summary>
    public partial interface IOrgHeaderRepository : IRepository<OrgHeader, string>, Abp.Dependency.ITransientDependency
    {
    }

}
